k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 188312700
  object_id: e31aeebf-3c36-49be-71b5-241bac97f345
  sha: sha256:d6a0e04f107d223795869aa839b1e504716c4d90f40411cc158bd565c4bef171
k3s/k3s:
  size: 72741048
  object_id: b1e7fac3-5b39-436f-4c51-6545c6fe4305
  sha: sha256:660c48d525e5fa2c2ddd889a25ce2c18c961e3046cc083cbde8557a8ff1ddb46
