k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 181647067
  object_id: ef1cf3b4-6aa1-4cb7-4ac4-33ac25fb957b
  sha: sha256:0bad9ede6ecd09461f9f73c44073e97f20e45c59556c0db61be93f8695fdf901
k3s/k3s:
  size: 73343160
  object_id: e513a4c0-9bc1-4ad6-4590-06bbdf9a5594
  sha: sha256:6f4012de542b9e831c1fcdb030645156aa4ca355202ea20ea5e544ae4ee1e650
