k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 181647067
  object_id: c3ab820a-3930-482b-67f8-9d11ae73a51d
  sha: sha256:9cc46db774c51e4195dfe3c2dafe1ecc18c7293bf08e7a81258aec07e60fc26d
k3s/k3s:
  size: 74305720
  object_id: f6b2ec23-d540-49f5-7706-9082d8a860b5
  sha: sha256:86945269160fdd1bbd06283ea5b3bafd6c0ec0d1df3ac68ad3686656632081a5
