k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 184770016
  object_id: 1f516b60-4047-48c9-733a-1044d643b265
  sha: sha256:499d7fb0b2eab200e9bf9b3935ce787a7fa0597933dce25ad091703933d6ecc8
k3s/k3s:
  size: 74903736
  object_id: c5832033-926f-49a4-6e23-00eade5073e6
  sha: sha256:f95350e3997165974d1d1406f01aabaf869aed7ca790cc2d83a92a82f26a06c5
