k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 182743205
  object_id: df5962da-d520-4baf-4df6-91f63ee0fb03
  sha: sha256:469e9ecafbd69565d8f55cb451ca968edbe7aa872bfd783acd3058bb3b1cbe01
k3s/k3s:
  size: 75555000
  object_id: 6171c759-5a14-445e-4327-4b500aa6656b
  sha: sha256:e406ca6e47673d747ab4665c90a9285615fe082e2593343725ed043ae163abbf
