k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 181647061
  object_id: 9f3bafc5-d00f-4c79-5fd2-64955928b03c
  sha: sha256:4bfa596bec42e8752d6f90e69e724ee438c2a8c3ba7827c3d4f30ca8ca30de35
k3s/k3s:
  size: 74834104
  object_id: a120151d-c0d4-4bb9-54b2-e473e167ee41
  sha: sha256:15811d34187e03fe29d0e46108c42cc33e62cec1b3d9d80f50944536ebcad40a
