k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 182743218
  object_id: 77dafaf1-2ccf-42e2-444e-1e73a5d572be
  sha: sha256:e4c4437580f6a2379963ed78d3a58212932fd4c917fc33c0664ce2a8b89fe389
k3s/k3s:
  size: 74608824
  object_id: 2449ad12-aca3-443d-6d71-879d4ce3351c
  sha: sha256:c1551a8bd32b690705df3faea84cfbd5bf8cea90aa0f41c75bfdc587656fd0d4
