k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 184770022
  object_id: f3b89720-35ee-4143-52c0-91cad373842f
  sha: sha256:47644f3141878535a1951fdaf03bc485001b50a58b8fb58d97c75c49ea38a1f0
k3s/k3s:
  size: 74399928
  object_id: 62c6b605-fcef-410d-6787-fd23ebb23fa4
  sha: sha256:8cb5e74c409635f73856d1956ca9b2402df3c72524b894299a891d3f05da399d
