k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 184770015
  object_id: 4e5e3888-6b18-4965-5ea5-cf73bb438d32
  sha: sha256:af7ce67f0a8c457618a492ba995cc645d8ad13512008b88db97719941c39389a
k3s/k3s:
  size: 75374776
  object_id: 3f605f74-fda5-4362-532e-52344933ca9e
  sha: sha256:959c9310a6ab893958d1c95bc5d7609de9d7884630c8832180f059369b6dc331
