k3s-images/k3s-airgap-images-amd64.tar.gz:
  size: 182743212
  object_id: 87f738df-0e17-4a4b-75a6-f5c8e7b64d06
  sha: sha256:ab5da5904db9b41df478fd59e526b5802902650e83a85674c6b19c51ad38b4a4
k3s/k3s:
  size: 75059384
  object_id: 0786333b-4f81-4840-6195-0803b89dd15b
  sha: sha256:94404b82a83468f5ea058652435f847ea3a7f6fbc3739b9e327e1c6e136db504
